export const FETCH_UNITY_LOADER = 'FETCH_UNITY_LOADER';
export const FETCH_UNITY_LOADER_SUCCESS = 'FETCH_UNITY_LOADER_SUCCESS';
export const FETCH_UNITY_LOADER_FAILURE = 'FETCH_UNITY_LOADER_FAILURE';

export const GAME_LAUNCHING = 'GAME_LAUNCHING';
export const LAUNCH_GAME = 'LAUNCH_GAME';
